version : '2'


services:


  nginx:
    image: raulr/nginx-wordpress
    depends_on:
     - wordpress
    volumes_from:
     - wordpress
    ports:
     - "8080:80"
    environment:
      POST_MAX_SIZE: 128m 
    networks:
    - back

  wordpress:
    depends_on:
      - db
    image: wordpress
    restart: always
    volumes:
      - ./wp-content:/var/www/html/wp-content
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_PASSWORD: p4ssw0rd!
    ports:
      - 80:80
      - 444:444
    networks:
      - back

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 8181:80
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: p4ssw0rd!
    networks:
      - back

  db: 
    image: mysql:5.7
    restart: always
    volumes: 
      - db_data:/var/lib/mysql
    environment: 
      MYSQL_ROOT_PASSWORD: p4ssw0rd!
    networks: 
      - back
        
networks:
  back:
volumes:
  db_data: